### ISSUE TITLE
Is the data.ttl OK?

### ISSUE THREAD

**Issue by ori-no** [michael-sevcik/NPRG036-Data-Formats#27] opened 2023-11-03 14:24 UTC
My uncertanties are: 
1. The prefixes - do they point exactly where they should? Are there not subsites they point to?
2. Known class definitions - ```(such as dbo:Street)``` do they need to be in the file?
3. Unknow class definitions - Do we need to add them to the start the file and the define them separately as shown in [slides02](https://docs.google.com/presentation/d/1SUiDAQNzpwzwthzN9ejNV4sxhx_UehH__mMplTNX9q8/edit#slide=id.g14b94fd94aa_0_161)?
If so then I think there should also be the known class definitions
4. Known Propery definitions - for example the ```dbo:area a rdf:Property``` which I left in the comment. Should it be there?

Please tell me what you think @michael-sevcik @patinoboh @rastoboh

**Comment by patinoboh** [comment] 2023-11-03 14:58
1. OK, wait for Kelimeks eval
2. According to assignment, everything has to be in one file.
3. I think it is fine both ways, maybe is more readable if you define them in the top and implement them with the copied definition.
4. dont know

As for the content, I'll be checking it throughout my following work with the file.
@ori-no

**Comment by patinoboh** [comment] 2023-11-03 15:51
I am not sure about the middle names array.
`
ex:middleNames a rdf:Property ;
	rdfs:label "Stredné mená"@sk ;
	rdfs:domain foaf:Person ;
	rdfs:range rdf:langString.
`
Might be correct, but I do not see any list in there. Do you think it's correct? How to make instance of two or more middle names?

**Comment by ori-no** [comment] 2023-11-03 15:56
@michael-sevcik discussed it with Klímek at practicals. I do think that this is the solution they came up with. But I would rather get final word from the author himself.

**Comment by patinoboh** [comment] 2023-11-03 16:54
# Update : 
If **middleNames** are ok, I see no additional problems with it yet.
@ori-no could you please finish the **area** and **hex_code** so I can create the instances and finish whole rdf section?
The instances only miss these attributes [as you can see here](https://github.com/michael-sevcik/NPRG036-Data-Formats/compare/main...22-example-instances-for-rdf-conceptual-model).
@ori-no

**Comment by patinoboh** [comment] 2023-11-03 23:06
Tried to fix the hex_code and are [https://github.com/michael-sevcik/NPRG036-Data-Formats/commit/08cf1f333aa55a08a88ded6f7cfb852c3b4ddb0c](here). The whole branch in [pull request](https://github.com/michael-sevcik/NPRG036-Data-Formats/pull/30)

**Comment by michael-sevcik** [comment] 2023-11-04 09:05
> @michael-sevcik discussed it with Klímek at practicals. I do think that this is the solution they came up with. But I would rather get final word from the author himself.

I can confirm that this the solution for `middleNames` approved during the practicals.

**Comment by michael-sevcik** [comment] 2023-11-04 11:59
@ori-no @patinoboh, I would rather use the definitions which also includes the labels etc. to keep the data consise.

**Comment by ori-no** [comment] 2023-11-05 10:32
@michael-sevcik I see the changes you did in data.ttl. I agree with everything and I see I wrongly defined the dbo:area here is its url https://dbpedia.org/ontology/area. But could the ex:area not be in the form of rdfs:subPropertyOf  which is very cool thing you did in others. Or there is other possibility, which I am not sure of, because the property dbo:area does not have domain defined. Does that mean that we can do whatever, or would it mean we can derive the subPropertyOf ?

**Comment by rastoboh** [comment] 2023-11-05 10:49
i think it means that we can do whatever because of not defined domain but i am not sure

**Comment by rastoboh** [comment] 2023-11-05 10:56
I am getting some kind of warning in instances.ttl in middlenames. Perhaps the parentheses could be changed to normal ones but again i am not sure

**Comment by michael-sevcik** [comment] 2023-11-06 07:13
Now with great honor, I hereby declare this issue closed as we had resolved it yesterday with all the beautiful commits.

**Closed by michael-sevcik** 2023-11-06 07:13 UTC
Labels: help wanted
